[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_source = '''
  " Start with insert-mode
  let g:unite_enable_start_insert = 1
  let g:unite_source_history_yank_enable = 1
  
  let g:unite_enable_ignore_case = 1
  let g:unite_enable_smart_case = 1
  
  let g:unite_source_file_mru_limit = 1000
  
  if executable('ag')
    let g:unite_source_grep_command = 'ag'
    let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
    let g:unite_source_grep_recursive_opt = '--nogroup --nocolor --column'
  endif
'''
hook_add = '''
  " View all buffer
  noremap <C-U><C-B> :Unite buffer<CR>
  " Vier all files
  noremap <C-U><C-F> :UniteWithBufferDir -buffer-name=files file<CR>
  " View history of yank
  noremap <C-U><C-Y> :Unite history/yank<CR>
  " View all registers
  noremap <C-U><C-R> :Unite -buffer-name=register register<CR>
  " Files and buffers
  noremap <C-U><C-U> :Unite buffer file_mru<CR>
  " All view
  noremap <C-U><C-A> :Unite -buffer-name=files buffer file_mru bookmark file<CR>
  " Search like ctrlp
  noremap <C-U><C-P> :Unite file_rec/async<CR>
  " Close unite
  au FileType unite nnoremap <silent> <buffer> <ESC><ESC> :q<CR>
  au FileType unite inoremap <silent> <buffer> <ESC><ESC> <ESC>:q<CR>
  
  " Search all files under current directory
  nnoremap <silent> ,g :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
  " Search under current directory with cursor's word
  nnoremap <silent> ,cg :<C-u>Unite grep:. -buffer-name=search-buffer<CR><C-R><C-W>
  " Re-open the search result
  nnoremap <silent> ,r :<C-u>UniteResume search-buffer<CR>
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_source = '''
  let g:vimfiler_enable_clipboard = 0
  let g:vimfiler_as_default_explorer = 1
'''
hook_add = '''
  nnoremap <silent> [Space]v :<C-u>VimFiler -invisible<CR>
'''
hook_post_source = '''
'''

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {
        \ "watchdogs_checker/ghc-mod" : {
        \   "command": "ghc-mod",
        \   "exec": '%c %o --hlintOpt="--language=XmlSyntax" check %s:p',
        \ },
        \
        \ "javascript/watchdogs_checker" : {
        \   "type": "eslint",
        \ },
        \ "haskell/watchdogs_checker" : {
        \   "type": "watchdogs_checker/ghc-mod",
        \ },
  \ }
  let g:quickrun_config['sql'] = {
        \ 'command': 'psql',
        \ 'exec': ['%c %o < %s'],
        \ 'cmdopt': '%{MakepgsqlCommandOptions()}',
        \ }
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = ['vim-quickrun', 'vimproc', 'shabadou.vim']
hook_add = '''
  let g:watchdogs_check_BufWritePost_enable = 1
  let g:watchdogs_check_CursorHold_enable = 1
'''
hook_post_source = 'call watchdogs#setup(g:quickrun_config)'

