[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
  " Start with insert-mode
  let g:unite_enable_start_insert = 1
  let g:unite_source_history_yank_enable = 1
  
  let g:unite_enable_ignore_case = 1
  let g:unite_enable_smart_case = 1
  
  let g:unite_source_file_mru_limit = 1000
  
  if executable('ag')
    let g:unite_source_grep_command = 'ag'
    let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
    let g:unite_source_grep_recursive_opt = '--nogroup --nocolor --column'
  endif
'''
hook_add = '''
  " View all bookmark
  noremap <C-U><C-B> :Unite bookmark<CR>
  " Vier all files
  noremap <C-U><C-F> :UniteWithBufferDir -buffer-name=files file<CR>
  " View history of yank
  noremap <C-U><C-Y> :Unite history/yank<CR>
  " View all registers
  noremap <C-U><C-R> :Unite -buffer-name=register register<CR>
  " Files and buffers
  noremap <C-U><C-U> :Unite buffer file_mru<CR>
  " All view
  noremap <C-U><C-A> :Unite -buffer-name=files buffer file_mru bookmark file<CR>
  " Search like ctrlp
  noremap <C-U><C-P> :Unite file_rec/async<CR>
  " Close unite
  au FileType unite nnoremap <silent> <buffer> <ESC><ESC> :q<CR>
  au FileType unite inoremap <silent> <buffer> <ESC><ESC> <ESC>:q<CR>
  
  " Search all files under current directory
  nnoremap <silent> ,g :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
  " Search under current directory with cursor's word
  nnoremap <silent> ,cg :<C-u>Unite grep:. -buffer-name=search-buffer<CR><C-R><C-W>
  " Re-open the search result
  nnoremap <silent> ,r :<C-u>UniteResume search-buffer<CR>

  call unite#custom#profile('default', 'context', {
        \   'start_insert': 1,
        \   'winheight': 15,
  \ })
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
  let g:vimfiler_enable_clipboard = 0
  let g:vimfiler_as_default_explorer = 1
'''
hook_add = '''
  nnoremap <silent> <Leader>z :<C-u>VimFilerBufferDir -split -simple -winwidth=45 -toggle -no-quit<CR>
'''
hook_post_source = '''
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = get(g:, 'quickrun_config', {})

  let g:quickrun_config['sql'] = {
        \ 'command': 'psql',
        \ 'exec': ['%c %o < %s'],
        \ 'cmdopt': '%{MakepgsqlCommandOptions()}',
        \ }

  " stop quickrun with <Ctrl-c>
  nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
'''
[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''

